/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.artgui.nutrisis.view;

/**
 *
 * @author Guilherme
 */
public class DlgCRUDRefeicao extends javax.swing.JDialog {

    /**
     * Creates new form DlgCRUDRefeicao
     */
    public DlgCRUDRefeicao(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panInputs = new javax.swing.JPanel();
        panNome4 = new javax.swing.JPanel();
        lblNome4 = new javax.swing.JLabel();
        edtNome4 = new javax.swing.JTextField();
        panDescricao = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        edtDescricao = new javax.swing.JTextField();
        panDiasDuracao = new javax.swing.JPanel();
        lblDiasDuracao = new javax.swing.JLabel();
        edtDiasDuracao = new javax.swing.JTextField();
        panIdNutricionista = new javax.swing.JPanel();
        lblIdNutricionista = new javax.swing.JLabel();
        edtIdNutricionista = new javax.swing.JTextField();
        panRefeicao = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        grdReceita = new javax.swing.JTable();
        lblTituloRefeicao = new javax.swing.JLabel();
        btnAddReceita = new javax.swing.JButton();
        btnRemoverReceita = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setBackground(new java.awt.Color(51, 51, 51));
        lblTitulo.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 204, 204));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CRUD Refeição");

        panInputs.setBackground(new java.awt.Color(40, 40, 40));

        panNome4.setBackground(new java.awt.Color(51, 51, 51));

        lblNome4.setBackground(new java.awt.Color(51, 51, 51));
        lblNome4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNome4.setForeground(new java.awt.Color(204, 204, 204));
        lblNome4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome4.setText("Nome");

        edtNome4.setBackground(new java.awt.Color(60, 60, 60));
        edtNome4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edtNome4.setForeground(new java.awt.Color(204, 204, 204));
        edtNome4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 30, 30), 1, true));

        javax.swing.GroupLayout panNome4Layout = new javax.swing.GroupLayout(panNome4);
        panNome4.setLayout(panNome4Layout);
        panNome4Layout.setHorizontalGroup(
            panNome4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNome4Layout.createSequentialGroup()
                .addComponent(lblNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtNome4))
        );
        panNome4Layout.setVerticalGroup(
            panNome4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNome4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(edtNome4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panDescricao.setBackground(new java.awt.Color(51, 51, 51));

        lblDescricao.setBackground(new java.awt.Color(51, 51, 51));
        lblDescricao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(204, 204, 204));
        lblDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescricao.setText("Horario");

        edtDescricao.setBackground(new java.awt.Color(60, 60, 60));
        edtDescricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edtDescricao.setForeground(new java.awt.Color(204, 204, 204));
        edtDescricao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 30, 30), 1, true));

        javax.swing.GroupLayout panDescricaoLayout = new javax.swing.GroupLayout(panDescricao);
        panDescricao.setLayout(panDescricaoLayout);
        panDescricaoLayout.setHorizontalGroup(
            panDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDescricaoLayout.createSequentialGroup()
                .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtDescricao))
        );
        panDescricaoLayout.setVerticalGroup(
            panDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(edtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panDiasDuracao.setBackground(new java.awt.Color(51, 51, 51));
        panDiasDuracao.setPreferredSize(new java.awt.Dimension(364, 50));

        lblDiasDuracao.setBackground(new java.awt.Color(51, 51, 51));
        lblDiasDuracao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDiasDuracao.setForeground(new java.awt.Color(204, 204, 204));
        lblDiasDuracao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiasDuracao.setText("Calorias");

        edtDiasDuracao.setBackground(new java.awt.Color(60, 60, 60));
        edtDiasDuracao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edtDiasDuracao.setForeground(new java.awt.Color(204, 204, 204));
        edtDiasDuracao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 30, 30), 1, true));

        javax.swing.GroupLayout panDiasDuracaoLayout = new javax.swing.GroupLayout(panDiasDuracao);
        panDiasDuracao.setLayout(panDiasDuracaoLayout);
        panDiasDuracaoLayout.setHorizontalGroup(
            panDiasDuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDiasDuracaoLayout.createSequentialGroup()
                .addComponent(lblDiasDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtDiasDuracao))
        );
        panDiasDuracaoLayout.setVerticalGroup(
            panDiasDuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDiasDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(edtDiasDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panIdNutricionista.setBackground(new java.awt.Color(51, 51, 51));
        panIdNutricionista.setPreferredSize(new java.awt.Dimension(364, 50));

        lblIdNutricionista.setBackground(new java.awt.Color(51, 51, 51));
        lblIdNutricionista.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblIdNutricionista.setForeground(new java.awt.Color(204, 204, 204));
        lblIdNutricionista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdNutricionista.setText("ID Nutricionista");

        edtIdNutricionista.setBackground(new java.awt.Color(60, 60, 60));
        edtIdNutricionista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edtIdNutricionista.setForeground(new java.awt.Color(204, 204, 204));
        edtIdNutricionista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 30, 30), 1, true));

        javax.swing.GroupLayout panIdNutricionistaLayout = new javax.swing.GroupLayout(panIdNutricionista);
        panIdNutricionista.setLayout(panIdNutricionistaLayout);
        panIdNutricionistaLayout.setHorizontalGroup(
            panIdNutricionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panIdNutricionistaLayout.createSequentialGroup()
                .addComponent(lblIdNutricionista, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtIdNutricionista))
        );
        panIdNutricionistaLayout.setVerticalGroup(
            panIdNutricionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIdNutricionista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(edtIdNutricionista, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panRefeicao.setBackground(new java.awt.Color(51, 51, 51));

        grdReceita.setBackground(new java.awt.Color(51, 51, 51));
        grdReceita.setForeground(new java.awt.Color(204, 204, 204));
        grdReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ));
        grdReceita.setGridColor(new java.awt.Color(51, 51, 51));
        grdReceita.setSelectionBackground(new java.awt.Color(0, 51, 102));
        grdReceita.setSelectionForeground(new java.awt.Color(153, 255, 255));
        jScrollPane3.setViewportView(grdReceita);

        lblTituloRefeicao.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTituloRefeicao.setForeground(new java.awt.Color(204, 204, 204));
        lblTituloRefeicao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRefeicao.setText("Receita");

        btnAddReceita.setBackground(new java.awt.Color(51, 51, 51));
        btnAddReceita.setForeground(new java.awt.Color(0, 255, 51));
        btnAddReceita.setText("Adiconar");
        btnAddReceita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 70, 70), 1, true));
        btnAddReceita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddReceita.setPreferredSize(new java.awt.Dimension(100, 50));
        btnAddReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddReceitaActionPerformed(evt);
            }
        });

        btnRemoverReceita.setBackground(new java.awt.Color(51, 51, 51));
        btnRemoverReceita.setForeground(new java.awt.Color(255, 102, 102));
        btnRemoverReceita.setText("Remover");
        btnRemoverReceita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 70, 70), 1, true));
        btnRemoverReceita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemoverReceita.setPreferredSize(new java.awt.Dimension(100, 50));
        btnRemoverReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverReceitaActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelar.setForeground(new java.awt.Color(255, 102, 102));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 70, 70), 1, true));
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 50));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(51, 51, 51));
        btnSalvar.setForeground(new java.awt.Color(0, 255, 51));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 70, 70), 1, true));
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panRefeicaoLayout = new javax.swing.GroupLayout(panRefeicao);
        panRefeicao.setLayout(panRefeicaoLayout);
        panRefeicaoLayout.setHorizontalGroup(
            panRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRefeicaoLayout.createSequentialGroup()
                .addGroup(panRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panRefeicaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panRefeicaoLayout.createSequentialGroup()
                                .addComponent(lblTituloRefeicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemoverReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panRefeicaoLayout.setVerticalGroup(
            panRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRefeicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoverReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panInputsLayout = new javax.swing.GroupLayout(panInputs);
        panInputs.setLayout(panInputsLayout);
        panInputsLayout.setHorizontalGroup(
            panInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panNome4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panDiasDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addComponent(panIdNutricionista, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addComponent(panRefeicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panInputsLayout.setVerticalGroup(
            panInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panNome4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDiasDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panIdNutricionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panRefeicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddReceitaActionPerformed

    private void btnRemoverReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverReceitaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgCRUDRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgCRUDRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgCRUDRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCRUDRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgCRUDRefeicao dialog = new DlgCRUDRefeicao(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddReceita;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemoverReceita;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtDescricao;
    private javax.swing.JTextField edtDiasDuracao;
    private javax.swing.JTextField edtIdNutricionista;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtNome1;
    private javax.swing.JTextField edtNome2;
    private javax.swing.JTextField edtNome3;
    private javax.swing.JTextField edtNome4;
    private javax.swing.JTable grdReceita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDiasDuracao;
    private javax.swing.JLabel lblIdNutricionista;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblNome3;
    private javax.swing.JLabel lblNome4;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloRefeicao;
    private javax.swing.JPanel panDescricao;
    private javax.swing.JPanel panDiasDuracao;
    private javax.swing.JPanel panIdNutricionista;
    private javax.swing.JPanel panInputs;
    private javax.swing.JPanel panNome;
    private javax.swing.JPanel panNome1;
    private javax.swing.JPanel panNome2;
    private javax.swing.JPanel panNome3;
    private javax.swing.JPanel panNome4;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panRefeicao;
    // End of variables declaration//GEN-END:variables
}
